### ISSUE TITLE
buffer is too small while converting Yolo weights

### ISSUE THREAD

**Issue by Borda** [Borda/keras-yolo3#6]
download the original model https://pjreddie.com/media/files/yolo.weights and run conversion via 
```bash
python convert_weights.py --config_path ../model_data/yolo.cfg --weights_path ../model_data/yolo.weights --output_path ../model_data/yolo.h5
```
crashes with folowing error message:
```
 73%|██████████████████████████▎                    | 79/108 [02:16<01:38,  3.41s/it]
Traceback (most recent call last):
  File "convert_weights.py", line 297, in <module>
    _main(**arg_params)
  File "convert_weights.py", line 267, in _main
    weights_file, count, weight_decay, out_index)
  File "convert_weights.py", line 168, in parse_section
    weight_decay)
  File "convert_weights.py", line 116, in parse_convolutional
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array
```

**Comment by Borda** [comment]
to run conversion without GPU use `CUDA_VISIBLE_DEVICES=-1 python ...`

**Comment by Borda** [comment]
similar to:
- https://github.com/allanzelener/YAD2K/issues/9 - https://github.com/allanzelener/YAD2K/issues/107
- https://github.com/qqwweee/keras-yolo3/issues/14 - https://github.com/qqwweee/keras-yolo3/issues/17
- https://github.com/hollance/YOLO-CoreML-MPSNNGraph/issues/26

**Comment by Borda** [comment]
similar to:
- https://github.com/allanzelener/YAD2K/issues/9 - https://github.com/allanzelener/YAD2K/issues/107
- https://github.com/qqwweee/keras-yolo3/issues/14 - https://github.com/qqwweee/keras-yolo3/issues/17
- https://github.com/hollance/YOLO-CoreML-MPSNNGraph/issues/26

**Comment by Borda** [comment]
double-check that you are working with the last version of YOLO v3 model
 (created after March 25 2018, [yolov3.weights](https://pjreddie.com/media/files/yolov3.weights) and/or [yolov3-tiny.weights](https://pjreddie.com/media/files/yolov3-tiny.weights))
